# Generated by Django 4.2 on 2023-04-22 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='content',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
